### ISSUE TITLE
Use new layout 

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/web-installer#1]
As discussed with @jancborchardt 😉 😷 

cc @MorrisJobke 😉

**Comment by hitam4450** [comment]
Maybe it could include optional apps to download and install at the same time to make it a ready-to-go solution ??

regards, hiatm4450

**Comment by MariusBluem** [comment]
Mhmm... I think this is not necessary, because it is as simple as you open the App Store after installing 😉 We should keep it as simple as possible.

**Comment by hitam4450** [comment]
Just an idea ...open for discussion! :smile:

**Comment by MariusBluem** [comment]
Done with 8ddb802 😉

**Comment by MorrisJobke** [comment]
Now looks like this:

<img width="1428" alt="bildschirmfoto 2016-08-01 um 16 45 54" src="https://cloud.githubusercontent.com/assets/245432/17298418/499fce3a-580a-11e6-86df-1cad69f752a3.png">

cc @jancborchardt
