### ISSUE TITLE
Method Not Implemented

### ISSUE THREAD

**Issue by elito** [nextcloud/web-installer#12]
Hi, can't find any answer on the web so  i post here.

I have this error 
**Method Not Implemented**
GET to /nextcloud/setup-nextcloud.php not supported.

when i access https://www.domain.fr/nextcloud/setup-nextcloud.php

Thank's for help.

**Comment by MorrisJobke** [comment]
Looks like a setup issue. Could you check if other php files work fine?

**Comment by elito** [comment]
Thank's for the reply it was an error with config file (.ovhconfig) from my hosting provider OVH.
Now it's OK.
