### ISSUE TITLE
Error in the installation - HTML Error 403 - forbidden

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/web-installer#16]
I started the web-installer ( version 11.0.2). and after the second step I receive the HTML Error forbidden!

Why ? In many installations before it worked like a charm!
after entering serverip/nextcloud/index.php it went to the final step!

However, after 2 weeks of desperate attempts, no LOGIN into mysql is possible!

![403](https://user-images.githubusercontent.com/9738727/28163657-5b652d2c-67cc-11e7-8552-7556eb30a729.png)

**Comment by MorrisJobke** [comment]
Please ask this in the forums. Looks like a problem with the permissions and apache.

https://help.nextcloud.com/
