### ISSUE TITLE
Nextcloud website's link to the web installer is older from this repository's version [HIGH PRIORITY]

### ISSUE THREAD

**Issue by siliconninja** [nextcloud/web-installer#18]
When going to https://nextcloud.com/install/#instructions-server > **Web Installer** menu, the "right-click here" link goes to https://download.nextcloud.com/server/installer/setup-nextcloud.php.

The version of Nextcloud it installs in this file is `11.0.0`. In this repository, the version it installs is `12.0.1`, as merged in https://github.com/nextcloud/web-installer/pull/15.

I am not sure if this is whether the `12.0.1` version isn't ready for the web-installer.php file or if it's just not set up on the website yet. There are [no Nextcloud forum issues about this](https://help.nextcloud.com/search?q=setup-nextcloud.php) yet. I'm posting this here because I want this issue to get more attention from official contributors and Nextcloud maintainers.

**Comment by MorrisJobke** [comment]
cc @LukasReschke @jospoortvliet

**Comment by jospoortvliet** [comment]
I guess this should be the latest 12.0.x indeed... Perhaps Monday/Tuesday is a good day to change this 🗡

**Comment by MariusBluem** [comment]
Fixed :)
