### ISSUE TITLE
NC mistaken PHP-FPM version 5.4.16 as PHP version

### ISSUE THREAD

**Issue by ghost** [nextcloud/web-installer#22]
as described [here](https://github.com/nextcloud/server/issues/8115#issuecomment-362078392) and requested by @rullzer

**Comment by ghost** [comment]
Is this being looked into?

after update to NC 12.0.5 it is not possible to log into NC. With the php-fpm server _running_ it shows
> This version of Nextcloud requires at least PHP 5.6.0
> You are currently running 5.4.16. Please update your PHP version.

And with the php-fpm server _stopped_ it gets
> 502 Bad Gateway

**Comment by rullzer** [comment]
@MorrisJobke do you have any idea why the installer allows you to install?

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have any idea why the installer allows you to install?

Not really - the check looks good. But this installer looks quite antique ... maybe we check it again to be compatible with the most recent changes and also just install on PHP 5.6+

**Comment by n8v8R** [comment]
server is now on PHP 7.1.9

see https://vtol.me/
and then https://vtol.me/nextcloud
