### ISSUE TITLE
Update to Nextcloud 13

### ISSUE THREAD

**Issue by TalusUnheil** [nextcloud/web-installer#23]
As of today, setup-nextcloud.php is still delivering Nextcloud 12.0.4 instead of Nextcloud 13. I think this should be updated.

**Comment by MorrisJobke** [comment]
cc @MariusBluem @jospoortvliet

**Comment by MariusBluem** [comment]
Let’s wait till 13.0.1 minor release ...

**Comment by microglossum** [comment]
This happened a couple days ago. Looking forward to 13.0.1 web-installer!
