### ISSUE TITLE
How do I use this to install on a local machine?

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/web-installer#26]
I have vague memories of using the web-installer to get NextCloud running on my home media server about a month ago when I was first toying with the idea of using it. Since then I have wiped my drive and tried a couple of other services like Cloudron. But I have decided to come back to NextCloud. 

I can't seem to get it to run the php file locally though. Uh... I know that php has to run on a server, or at least I think so because I usually have to run a server on my windows machine in my Mamp stack etc. So I'm not surprised it doesn't run but I'm also not sure what I did last month. I might have just used an AppImage or Snap, I'm uinsure but I seem to remember there being a webinstaller but I can't find any information on how to install it locally, everything talks about installing it to shared hosting.

**Comment by MariusBluem** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: [https://help.nextcloud.com](https://help.nextcloud.com)

**Comment by jcklpe** [comment]
Sure thing! Thanks. I've done so and have received help :)
