### ISSUE TITLE
Total Mess

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/web-installer#3]
After opening https://download.nextcloud.com/server/installer/setup-nextcloud.php
I received the following screen:

![nextcwebinst](https://cloud.githubusercontent.com/assets/9738727/18231821/183e97a8-72c3-11e6-99ca-1610b011f6fd.png)
What happened to the web-installer.php?
regards, hitam4450

Ss. Or did I miss something ????

**Comment by MeCias** [comment]
You wasn't reading the instruction properly, you just was hitting the "here" link. The installer does not work that way, you have to run it on your own server.

```
1. Right-click "here" and save the file to your computer
2. Upload setup-nextcloud.php to your web space
3. Point your web browser to setup-nextcloud.php on your webspace
4. Follow the instructions and configure Nextcloud
5. Login to your newly created Nextcloud instance!
```

**Comment by hitam4450** [comment]
Thanks for your answer!

**Comment by phsc84** [comment]
Obviously, this issue could be clarified and therefore can be closed.
