### ISSUE TITLE
old version on webpage download

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/web-installer#40]
when I download the setup-nextcloud.php file from the webpage in the .php file the version is 
define('NC_VERSION', '16.0.3');

I know in the source code it's latest. Maybe somebody know why the php file didn't get an update
https://nextcloud.com/install/#instructions-server

**Comment by gratuxri** [comment]
Please vote https://github.com/nextcloud/web-installer/issues/38 issue

**Comment by gratuxri** [comment]
Hello, please close this issue, because of "define('NC_VERSION', 'latest');" in https://download.nextcloud.com/server/installer/setup-nextcloud.php
