### ISSUE TITLE
Wrong redirect when using sqlite db

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/web-installer#42]
If you are installing Nextcloud with the web-installer and using sqlite as database (didn't try with other databases) on a host `myhost.mydomain.com` and directory `my-nc-dir`, the final step redirects the browser to `http://my-nc-dir/index.php/core/apps/recommended` instead of `http://myhost.mydomain.com/my-nc-dir/index.php/core/apps/recommended`

![image](https://user-images.githubusercontent.com/85954408/128332262-dace2e10-6632-44cc-8f52-d16787883f9d.png)

![image](https://user-images.githubusercontent.com/85954408/128332360-7f1c4535-4b49-44e2-9a4b-219199ee0db9.png)

![image](https://user-images.githubusercontent.com/85954408/128332575-6678ff40-9af9-4c3c-9b99-0efeeda18017.png)

![image](https://user-images.githubusercontent.com/85954408/128332665-0efa7971-419f-4aab-a835-4718d470ef51.png)

![image](https://user-images.githubusercontent.com/85954408/128332787-1267a589-798b-4a5d-b494-d9a22630ab1b.png)

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/27575
