### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jerrygreen** [nextcloud/web-installer#48]
I tried `php -f setup-nextcloud.php` but this ain't doing anything

```
mkdir ~/nextcloud
cd ~/nextcloud
curl -O https://download.nextcloud.com/server/installer/setup-nextcloud.php
php -f setup-nextcloud.php
```

It does nothing.

**Comment by ghost** [comment]
You need to setup web server with PHP
or for testing purposes you can `php -S localhost:port` and go to `localhost:port/setup-nextcloud.php`

**Comment by jerrygreen** [comment]
The question was related to properly installing into the system rather than initial setup

I kind of hoped there’s some script like `curl nextcloud.com | bash` or something

I ended up installing it with snap, though I don’t really like snap but it’s okay
