### ISSUE TITLE
After install, themes are broken, rendering site unusable

### ISSUE THREAD

**Issue by coyoteconscious** [nextcloud/web-installer#50]
The install at /setup-nextcloud.php seemed to go well, but afterward, upon logging in, themes are broken, and the site is nearly un-navigable.

The theme settings page is too broken to select another theme, and selecting another theme via occ also seems to have no effect.
I saw similar issues from other install methods described and tried several suggestions, to no avail:

```
occ maintenance:theme:update - no effect
occ user:setting administrator accessibility theme dark - no effect
occ user:setting administrator accessibility theme light - no effect
occ app:disable theming - error: theming can't be disabled.
```
also tried updating via occ - got a message saying everything is up to date.
Getting errors in logs such as:
```
024/02/12 08:29:08 [error] 2204#2204: *508 open() "/var/www/my.obfuscated-url.local/index.php/apps/theming/theme/dark-highcontrast.css" failed (20: Not a directory), client: (myipaddress), server: my.obfuscated-url.local, request: "GET /index.php/apps/theming/theme/dark-highcontrast.css?plain=1&v=e8053a31 HTTP/1.1", host: "my.obfuscated-url.local"
```
Not sure what it could be. I used an nginx template based off one from a previous server that worked fine (v24 nextcloud).

```
upstream php-handler {
    #server 127.0.0.1:9000;
    server unix:/var/run/php/php8.2-fpm.sock;
}

server {
    listen 80;
    listen [::]:80;
    ssl_certificate     /etc/letsencrypt/live/obfuscated.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/obfuscated.domain/privkey.pem;
    server_name my.obfuscated.domain.domain;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name my.obfuscated.domain.domain;
    root /var/www/my.obfuscated.domain.domain;
    ssl_certificate /etc/letsencrypt/live/obfuscated.domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/obfuscated.domain/privkey.pem; # managed by Certbot

    index index.php index.html index.htm index.nginx-debian.html;


    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~* /wp-sitemap.*\.xml {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    client_max_body_size 512M;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        include snippets/fastcgi-php.conf;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 128k;
        fastcgi_intercept_errors on;
    }

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_disable "msie6";
    gzip_types
    application/atom+xml
    application/geo+json
    application/javascript
    application/x-javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rdf+xml
    application/rss+xml
    application/xhtml+xml
    application/xml
    font/eot
    font/otf
    font/ttf
    image/svg+xml
    text/css
    text/javascript
    text/plain
    text/xml;

    # assets, media
    location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
        expires    90d;
        access_log off;
    }

    # svg, fonts
    location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
        add_header Access-Control-Allow-Origin "*";
        expires    90d;
        access_log off;
    }

    location ~ /\.ht {
        access_log off;
        log_not_found off;
        deny all;
    }

}
```
I've double-checked php settings and all that, increased memory, script timeouts, that sort of stuff. Nothing looks off there, and phpinfo shows the settings being honored.

Any ideas? I've been seeing other people have similar problems going back a while, but no solution to my problem. I've seen a couple posts around the net that are the _specific_ problem I'm having (w/ same errors), but nobody responded in those forums.

**Comment by coyoteconscious** [comment]
In the absence of any sign of life here, I did a manual install from scratch, without using the script, but attempting to follow _only_ the items handled in the script, and that worked. I can't quite tell what isn't working when the script installs it versus doing it by hand.

So, unless a dev or someone here notices and responds, I'm afraid I've got nothing on why this won't work for me. No solution. I guess, try not installing nextcloud using this script if you encounter this issue (but most people don't have the issue)?

**Comment by FungY911** [comment]
+1

**Comment by joshtrichards** [comment]
> Not sure what it could be. I used an nginx template based off one from a previous server that worked fine (v24 nextcloud).

The cause is - I believe - that you're using an outdated/unofficial config. Use the one in the docs: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

:)
